_target_: src.networks.aanet.Vanilla
input_shape: 100
n_archetypes: 4
layer_widths: [128, 128]
activation_out: "tanh"
simplex_scale: 1
archetypal_weight: 1.0
kl_loss: "partial"
lr: 0.001
optimizer: adam
