wandb:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  project: "ManyLatents"
  name: ${name}
  log_model: false
  save_dir: "."
  offline: False 
  id: null
  # entity: "" 
  prefix: ""
  job_type: "train"
  group: "" ## use slurmjobid env var to group e.g. ${oc.env:SLURM_JOB_ID}
  tags: []