site_name: ManyLatents
theme:
  name: material

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.highlight
  - tables
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: index.md
  - Algorithms: algorithms.md
  - Evaluation: evaluation.md
  - Callbacks: callbacks.md
  - Metrics: metrics.md
  - Extensions: extensions.md
  - API: api_usage.md
  - Probing: probing.md
  - Testing: testing.md
