site_name: ManyLatents
theme:
  name: material

nav:
  - Home: index.md
  - Extensions: extensions.md
  - Testing: testing.md
  - Architecture:
    - Metrics: metrics_architecture.md
    - API Usage: api_usage.md
