defaults:
  - base_config
  - _self_
  - data: null
  - callbacks: default
  - hydra: default
  - algorithm/latent: null
  - algorithm/lightning: null
  - pipeline: null
  - metrics: null
  - trainer: null # instantiate only if network is being passed
  - experiment: null

pipeline: []