# @package _global_
#
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    # partition: long-cpu
    #tasks_per_node: 1
    cpus_per_task: 4
    mem_gb: 64
    #mem_per_cpu: null
    timeout_min: 60
    array_parallelism: 10 # max num of tasks to run in parallel (via job array)
    setup:
      - "source .venv/bin/activate"

    additional_parameters:
      account: ctb-hussinju
