# @package _global_

defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    # partition: long
    gres: gpu:1
    # mem_per_gpu: 20
    mem_gb: null
    # mem_per_cpu: null
    mem_per_cpu: 128GB
    # cpus_per_gpu: 1
    timeout_min: 5000
    array_parallelism: 20 # max num of tasks to run in parallel (via job array)
    setup:
      - "source .venv/bin/activate"

    additional_parameters:
      account: def-hussinju

