# @package _global_
#
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: long
    #tasks_per_node: 1
    #additional_parameters: {array: 1-50%10}
    cpus_per_task: 1
    mem_gb: null
    mem_per_cpu: 128GB
    timeout_min: 2000
    array_parallelism: 30 # max num of tasks to run in parallel (via job array)
    setup:
      - "source .venv/bin/activate"
