_target_: manylatents.algorithms.latent.phate.PHATEModule
n_components: 2
random_state: ${seed}
knn: 5
t: 5
gamma: 1.0
decay: 40
n_pca: null #100 #default in source library
n_landmark: null
n_jobs: -1
verbose: False
fit_fraction: 1.0
neighborhood_size: ${neighborhood_size}
backend: null
device: null
