_target_: manylatents.algorithms.latent.diffusion_map.DiffusionMapModule
n_components: 2
random_state: ${seed}
t: 5
knn: 15
decay: 40
n_pca: null
n_landmark: null
n_jobs: -1
verbose: False
fit_fraction: 1.0
neighborhood_size: ${neighborhood_size}
mode: cluster
n_clusters: auto
