defaults:
  - default

_target_: src.algorithms.aa.ArchetypalAnalysisModule
n_components: 50  # number of archetypes
method: pgd     # or 'mu' (multiplicative updates)
max_iter: 100
random_state: ${seed}
