defaults:
  - default

_target_: src.algorithms.diffusionmap.DiffusionMapModule
n_components: 2
t: 5
knn: 100
decay: 40
n_pca: null
n_landmark: null
n_jobs: -1
verbose: False
# All other settings will be inherited from default.yaml
