_target_: src.algorithms.mds.MDSModule
ndim: 2
seed: ${seed}
how: metric   #  choose from ['classic', 'metric', 'nonmetric']
solver: smacof  # choose from ["sgd", "smacof"]
distance_metric: euclidean  # recommended values: 'euclidean' and 'cosine'
n_jobs: -1
verbose: False
fit_fraction: 1.0
