defaults:
  - network: null # specify a neural network
  - _self_

_target_: src.algorithms.tsne.TSNEModule

n_components: 2
random_state: 42
perplexity: 30
n_iter: 1000
learning_rate: 'auto'
metric: "euclidean"
fit_fraction: 1.0

