defaults:
  - default

_target_: src.algorithms.tsne.TSNEModule
n_components: 2
perplexity: 30
n_iter_early: 250
n_iter_late: 750
learning_rate: 'auto'
metric: "euclidean"
initialization: "pca"
# All other settings will be inherited from default.yaml