defaults:
  - default

_target_: src.algorithms.umap.UMAPModule
n_components: 2
n_neighbors: 15
min_dist: 0.5
n_epochs: 500
metric: 'euclidean'
learning_rate: 1.0
# All other settings will be inherited from default.yaml