defaults:
- _self_
# - dataset:
#   - geographic_preservation
#   - admixture_preservationk
- embedding:
  # - trustworthiness
  - knn_preservation
# - module:
#   - connected_components
subsample_fraction: 0.001
