defaults:
- _self_
- dataset:
  - gt_preservation
  - gt_preservation_far
- embedding:
  - knn_preservation
  - tangent_space
  - participation_ratio
  - continuity
  - trustworthiness
  - anisotropy
