defaults:
  - paths: default
  - data: default
  - hyperparameters: default
  - embeddings: phate
  - _self_

project:
  name: "PHATE_Hyperparameter_Search"
  repo_root: "${hydra:runtime.cwd}"
  log_level: "INFO"
