defaults:
  - base_config
  - _self_
  - data: null
  - callbacks: default
  - hydra: default
  - algorithm: default
  - metrics: default
  - trainer: null # instantiate only if network is being passed
  - experiment: null

seed: 2
debug: false