defaults:
  - base_config
  - _self_
  - data: null
  - callbacks: default
  - hydra: default
  - algorithms: null
  - metrics: null
  - trainer: null # instantiate only if network is being passed
  - experiment: null

seed: 2
debug: false
project: ManyLatents

# Trainer configuration
trainer:
  max_epochs: 1
  gpus: 0

# Callbacks configuration
callbacks:
  embedding: {}