## deprecated in current form, ignore
admixture_files:
  - "global.2_metadata.tsv"
  - "global.3_metadata.tsv"
  - "global.4_metadata.tsv"
  - "global.5_metadata.tsv"
  - "global.6_metadata.tsv"
  - "global.7_metadata.tsv"
  - "global.8_metadata.tsv"
  - "global.9_metadata.tsv"
admixtures_k: [2, 3, 4, 5, 6, 7, 8, 9]
## more files
metadata_file: "gnomad_derived_metadata_with_filtered_sampleids.csv" ## currently assumes that the metadata is in the same directory as the genotype files
relatedness_file: "HGDP+1KGP_MattEstimated_related_samples.tsv"
genotype_prefix: "gnomad.genomes.v3.1.2.hgdp_tgp.PASSfiltered.newIDs.onlySNPs.noDuplicatePos.noMiss5perc.match1000G_GSAs_dietnet"
pca_file: "pca_scores_hailcomputed.csv"
filters:
  - "filter_pca_outlier"
  - "hard_filtered"
  - "filter_contaminated"
