_target_: src.datamodules.hgdp.HGDPDataModule
plink_prefix: "gnomad.genomes.v3.1.2.hgdp_tgp.PASSfiltered.newIDs.onlySNPs.noDuplicatePos.noMiss5perc.match1000G_GSAs_dietnet"  # Path to PLINK file prefix
metadata_path: "gnomad_derived_metadata_with_filtered_sampleids.csv"  # Path to metadata
batch_size: 32
num_workers: 4
mode: "genotypes"
mmap_mode: null