defaults:
  - default

_target_: src.datamodules.hgdp.HGDPDataModule
mode: "genotypes"
mmap_mode: null

filenames:
  plink:  "gnomad.genomes.v3.1.2.hgdp_tgp.PASSfiltered.newIDs.onlySNPs.noDuplicatePos.noMiss5perc.match1000G_GSAs_dietnet"
  metadata: "gnomad_meta_updated.tsv"