_target_: src.datamodules.hgdp.HGDPDataModule
plink_prefix: "gnomad.genomes.v3.1.2.hgdp_tgp.PASSfiltered.newIDs.onlySNPs.noDuplicatePos.noMiss5perc.match1000G_GSAs_dietnet"
metadata_path: "gnomad_meta_updated.tsv"
mode: "genotypes"
mmap_mode: null