plot_embeddings:
  _target_: src.callbacks.embedding.plot_embeddings.PlotEmbeddings
  save_dir: ${hydra:runtime.output_dir}
  experiment_name: "${name}.png"
  figsize: [8, 6]
  legend: false
  color_by_score: null

