defaults:
  - override /data: swissroll
  - override /metrics/embedding: [trustworthiness, continuity, knn_preservation]
  - override /metrics/module: [affinity_spectrum]

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      algorithms/latent: umap,umap_torchdr,tsne,tsne_torchdr
      seed: 42,43,44
