defaults:
  - override /algorithms/latent: phate
  - override /data: swissroll
  - override /metrics/embedding: [trustworthiness, continuity, knn_preservation]

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      algorithms.latent.knn: 3,5,10,15,30
      algorithms.latent.t: 5,15,50,100
      seed: 42,43,44
