_target_: src.algorithms.reconstruction.Reconstruction
datamodule: ${data}
network:
  _target_: src.algorithms.networks.aanet.Vanilla
  ## would a partial call work?
  input_shape: null # must be currently specified from experiment 
  n_archetypes: 4
  layer_widths: [128, 128]
  activation_out: "tanh"
  simplex_scale: 1
  archetypal_weight: 1.0
  kl_loss: "partial"
  lr: 0.001
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
