_target_: manylatents.algorithms.lightning.reconstruction.Reconstruction
_recursive_: false
datamodule: ${data}
network:
  _target_: manylatents.algorithms.lightning.networks.aanet.Vanilla
  input_dim: null # inferred from data in setup()
  n_archetypes: 4
  layer_widths: [128, 128]
  activation_out: "tanh"
  simplex_scale: 1
  archetypal_weight: 1.0
  kl_loss: "partial"
  lr: 0.001
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
loss:
  _target_: manylatents.algorithms.lightning.losses.mse.MSELoss
