wandb_log_scores:
      _target_: manylatents.callbacks.embedding.wandb_log_scores.WandbLogScores
      log_summary:    true
      log_table:      true
      log_k_curve_table: true
      log_scree_plot: true
      include_labels: false
