defaults:
  - network: null # specify a neural network
  - dimensionality_reduction: null # specify a dimensionality reduction algorithm
  - _self_

_target_: src.algorithms.pca.PCA
_partial_: true

n_components: 50
random_state: 42

