defaults:
  - network: null # specify a neural network
  - dimensionality_reduction: null # specify a dimensionality reduction algorithm
  - _self_

_target_: src.algorithms.phate.PHATE
_partial_: true

n_components: 2
random_state: 42
t: 5
knn: 5
gamma: 1.0