defaults:
  - network: null # specify a neural network
  - dimensionality_reduction: null # specify a dimensionality reduction algorithm
  - _self_

_target_: src.algorithms.pca.PCA
_partial_: true

n_components: 2
random_state: 42
perplexity: 30
kwargs:
  n_iter: 1000
  learning_rate: 'auto'
  metric: "euclidean"

