additional_metrics:
  _target_: src.callbacks.dimensionality_reduction.additional_metrics.AdditionalMetrics
  trustworthiness: ## currently uses the sklearn implementation. ugly interfacing.
    n_neighbors: 5
    metric: euclidean
  metadata: null 

