additional_metrics:
  _target_: src.callbacks.dimensionality_reduction.additional_metrics.AdditionalMetrics
  trustworthiness:
    _target_: src.metrics.trustworthiness.Trustworthiness
    _partial_: True
    n_neighbors: 5
    metric: euclidean
metadata: null


