additional_metrics:
  _target_: src.callbacks.dimensionality_reduction.AdditionalMetrics
  trustworthiness:
    _target_: sklearn.manifold.trustworthiness
    _partial_: true
    n_neighbors: 5
    metric: euclidean
  metadata: null 

