additional_metrics:
  _target_: src.callbacks.dimensionality_reduction.AdditionalMetrics
  metrics_config:
      trustworthiness:
        _target_: src.metrics.dimensionality_reduction.Trustworthiness
        n_neighbors: 5
        metric: euclidean
  metadata: null 

