additional_metrics:
  _target_: src.callbacks.dimensionality_reduction.additional_metrics.AdditionalMetrics
  trustworthiness:
    _target_: src.metrics.trustworthiness.Trustworthiness
    _partial_: True
    n_neighbors: 5
    metric: euclidean
  admixture_preservation:
    _target_: src.metrics.preservation.AdmixturePreservation
    _partial_: True
  geographic_preservation:
    _target_: src.metrics.preservation.GeoPreservation
    _partial_: True
    use_medians: False
    only_far: False
metadata: null


