save_embeddings:
  _target_: src.callbacks.dimensionality_reduction.save_embeddings.SaveEmbeddings
  save_dir: ${hydra:runtime.output_dir}
  save_format: "csv"
  experiment_name: ${name}
  include_metrics: False